### ISSUE TITLE
httpx.InvalidURL: Invalid non-printable ASCII character in URL

### ISSUE THREAD

**Issue by bit1001** [zxyge/tg_file_download_bot#5]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/tg_file_download_bot/WebStreamer/utils/media_download.py", line 129, in workers
    send_msg(m, text)
  File "/root/tg_file_download_bot/WebStreamer/utils/media_download.py", line 99, in send_msg
    httpx.get(url)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_api.py", line 189, in get
    return request(
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 801, in request
    request = self.build_request(
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 346, in build_request
    url = self._merge_url(url)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_client.py", line 376, in _merge_url
    merge_url = URL(url)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_urlparse.py", line 160, in urlparse
    raise InvalidURL("Invalid non-printable ASCII character in URL")
httpx.InvalidURL: Invalid non-printable ASCII character in URL

**Comment by whistle003** [comment]
我也遇到了这个问题，请问大佬解决了吗？

**Comment by WizisCool** [comment]
同样的问题

**Comment by whistle003** [comment]
用我fork修改过的版本吧，已修复这个问题
